### ISSUE TITLE
ios app not subscribed to channel

### ISSUE THREAD

**Issue by Najeeb8680** [HomeXLabs/pusher-websocket-flutter#10]

**Comment by Najeeb8680** [comment]
please respond ASAP

**Comment by MisterJimson** [comment]
Please provide details, error messages, and if possible a reproducible for us to look at.

**Comment by Najeeb8680** [comment]
> Please provide details, error messages, and if possible a reproducible for us to look at.

No error messages, public channel works but private channel is not subscribe. i use authentication as well for private channel.

**Comment by Najeeb8680** [comment]
any solution???

**Comment by MisterJimson** [comment]
Please only leave comments that would help solve the problem. I can't give any timeline for when this will be looked it.

**Comment by HoangKimDuc** [comment]
me too!

**Comment by joakiwpc** [comment]
I have the same problem!!!

The problem is that I try to subscribe to a presence channel, nothing happens and no error is given. I can subscribe to public channels and on Android works perfectly.

**Comment by MisterJimson** [comment]
Thanks for the info @joakiwpc.

Do you know what domain you needed to add?

**Comment by Najeeb8680** [comment]
Issue is when you use [connectivity](https://pub.dev/packages/connectivity) plugin with [pusher_websocket_flutter](https://pub.dev/packages/pusher_websocket_flutter) plugin.

The solution is you must use another internet check connection like [data_connection_checker](https://pub.dev/packages/data_connection_checker) plugin with pusher_websocket_flutter
