### ISSUE TITLE
can i use pusher-websocket-flutter to send notification to android and ios 

### ISSUE THREAD

**Issue by Ahmedtaha123** [HomeXLabs/pusher-websocket-flutter#12]
now i wanna use real time data base and send notification to android and ios 
pusher-websocket-flutter can do this

**Comment by MisterJimson** [comment]
I would checkout the official Pusher website and see if it fits your needs.

https://pusher.com/

However pusher does not offer a realtime database. Firebase does. https://firebase.google.com/docs/database
