### ISSUE TITLE
Pusher Options host (ip or domain)

### ISSUE THREAD

**Issue by LtotheWT** [HomeXLabs/pusher-websocket-flutter#17]
Im currently using raspberry to test the websocket;
Must the Pusher Options host be a domain (ws.pusherapp.com) or can it be local IP address ?

**Comment by MisterJimson** [comment]
Pusher does not support self hosting as far as I know. Their server SDK just connects to their backend. So I do not believe you could use a local IP.

May be able to find more info on the official docs: https://pusher.com/docs/channels
