### ISSUE TITLE
get socket id

### ISSUE THREAD

**Issue by MohammedYAmmar** [HomeXLabs/pusher-websocket-flutter#18]
how can i get the socket id

**Comment by MisterJimson** [comment]
There is no way currently. What do you need it for?

**Comment by MohammedYAmmar** [comment]
I want it to do this 
https://pusher.com/docs/channels/server_api/excluding-event-recipients

plz read that link

**Comment by MisterJimson** [comment]
Available in 0.2.0. Thanks again!
