### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by KuroBech** [HomeXLabs/pusher-websocket-flutter#27]
Good night to who created this library.

Today I come with a question to you, since I would like to implement push notifications through pusher in my flutter app, I look forward to your response

**Comment by MisterJimson** [comment]
This library wrap the Pusher Channels product: https://pusher.com/channels

Pusher Channels is for real time information using websockets while your application is in the foreground.

For Pusher's Push Notification product, checkout: https://pusher.com/beams
