### ISSUE TITLE
Display white screen and app stuck on ios build using swift

### ISSUE THREAD

**Issue by Najeeb8680** [HomeXLabs/pusher-websocket-flutter#9]

**Comment by MisterJimson** [comment]
Can you add a little bit of detail here? There is a flutter issue open currently where the build will hang sometimes and you need to restart it. Maybe you ran into that?

**Comment by Najeeb8680** [comment]
I found the solution. When i use [connectivity](https://pub.dev/packages/connectivity) plugin with pusher_websocket_flutter it hangs on ios and crashes after 5 to 8 seconds. So i removed connectivity plugin and use another one then app works fine. We can only use connectivity or pusher_websocket_flutter plugin in an app. Now i am closing the issue.

**Comment by AleksandarSavic95** [comment]
> I found the solution. When i use [connectivity](https://pub.dev/packages/connectivity) plugin with pusher_websocket_flutter it hangs on ios and crashes after 5 to 8 seconds. So i removed connectivity plugin and use [data_connection_checker](https://pub.dev/packages/data_connection_checker) then app works fine. We can only use connectivity or pusher_websocket_flutter plugin in an app. Now i am closing the issue.

Thank You! This fixed my issue with iOS build stuck on white screen.
